### ISSUE TITLE
Adding fake-useragent

### ISSUE THREAD

**Issue by pcinkh** [lorien/awesome-web-scraping#30]
Hey, guys!

What section I need use to put fake-useragent library for python
This lib provides generation user agent strings based on the world browsers statistic.
[fake-useragent](https://github.com/hellysmile/fake-useragent)

I'm not sure, but I've made [pull request](https://github.com/lorien/awesome-web-scraping/pull/31/commits)

If this satisfies to guidelines, please merge that.

Thank's!

**Comment by lorien** [comment]
Thanks pcinkh. See my comment in pool request.
