### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by liar666** [lorien/awesome-web-scraping#41]
In Java,

There is:
- Heritrix
http://www.crawler.archive.org/index.html
which is hard to understand and seldomly supported.
- Norconex Collector
https://www.norconex.com/enterprise-search-software/open-source-crawlers/
which is actively developped and the main dev is very supportive.

**Comment by lorien** [comment]
Please clone the repo, add these libs to appropriate categories and then create the pull request. Thanks.
